# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /media/eric/storage_linux_2/dev/Linux_Unreal_Engine_5.3.2
GAMEPROJECTFILE =/media/eric/storage_linux_2/projects/MonoGrinding/MonoGrinding.uproject

TARGETS = \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Shipping  \
	UnrealEditor \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Shipping  \
	UnrealGame \
	MonoGrinding-Linux-DebugGame  \
	MonoGrinding-Linux-Shipping  \
	MonoGrinding \
	MonoGrindingEditor-Linux-DebugGame  \
	MonoGrindingEditor-Linux-Shipping  \
	MonoGrindingEditor\
	configure

BUILD = bash "$(UNREALROOTPATH)/Engine/Build/BatchFiles/Linux/Build.sh"
PROJECTBUILD = "$(UNREALROOTPATH)/Engine/Binaries/ThirdParty/DotNet/6.0.302/linux/dotnet" "$(UNREALROOTPATH)/Engine/Binaries/DotNET/UnrealBuildTool/UnrealBuildTool.dll"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MonoGrindingEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MonoGrindingEditor-Linux-Debug


UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Shipping:
	 $(BUILD) UnrealEditor Linux Shipping  $(ARGS)

UnrealEditor:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

MonoGrinding-Linux-DebugGame:
	 $(PROJECTBUILD) MonoGrinding Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MonoGrinding-Linux-Shipping:
	 $(PROJECTBUILD) MonoGrinding Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MonoGrinding:
	 $(PROJECTBUILD) MonoGrinding Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

MonoGrindingEditor-Linux-DebugGame:
	 $(PROJECTBUILD) MonoGrindingEditor Linux DebugGame  -project="$(GAMEPROJECTFILE)" $(ARGS)

MonoGrindingEditor-Linux-Shipping:
	 $(PROJECTBUILD) MonoGrindingEditor Linux Shipping  -project="$(GAMEPROJECTFILE)" $(ARGS)

MonoGrindingEditor:
	 $(PROJECTBUILD) MonoGrindingEditor Linux Development  -project="$(GAMEPROJECTFILE)" $(ARGS)

configure:
	xbuild /property:Configuration=Development /verbosity:quiet /nologo "$(UNREALROOTPATH)/Engine/Source/Programs/UnrealBuildTool/UnrealBuildTool.csproj"
	$(PROJECTBUILD) -projectfiles -project="\"$(GAMEPROJECTFILE)\"" -game -engine 

.PHONY: $(TARGETS)
